version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: medcof_db
    ports:
      - '27017:27017'