version: '3.8'

services:
  mongo:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: medcof_db
    ports:
      - '27017:27017'
