name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: "4000"
          envkey_DATABASE_URL: "mongodb://usr:password@localhost:27017/medcof_db?authSource=admin"
          envkey_JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          directory: ${GITHUB_WORKSPACE}
          file_name: .env
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run mongo npm run test