name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
            echo "${{ secrets.TEST_ENV }}" > .env.test  
            npm install
      - name: Docker build
        run: docker-compose -f docker-compose-test.yml --env-file .env.test up --build mongo
      - name: Run tests
        run: npm run test